PORTAL-1538: add new governmentInfo fields used for vn
Unicity/PublicModels.json pull request #17
Opened 2024-09-16 20:53 UTC by daintablian

2024-09-17 17:00 UTC, bluetechy requested changes

2024-09-17 17:00 UTC, bluetechy commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainerName": {
@daintablian The API has consistently followed this object model for names: https://github.com/Unicity/PublicModels.json/blob/master/src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Order.json#L146-L149

2024-09-17 17:00 UTC, bluetechy commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"idIssuedDate": {
@daintablian The API has consistently followed the naming convention date*******. For example: https://github.com/Unicity/PublicModels.json/blob/master/src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Order.json#L39-L62

2024-09-23 17:58 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainerName": {
Am I know following what here is not the object model?

2024-09-23 17:58 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainDate": {
done

2024-09-23 17:58 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"cardDate": {
done

2024-09-23 17:58 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainingCardDate": {
done

2024-09-23 17:58 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"idIssuedDate": {
done

2024-09-30 18:01 UTC, merged

2024-09-30 18:12 UTC, bluetechy commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainerName": {
@daintablian Originally, we had this object model called `identification`, but that was used in markets where they had more than one government id.  This looks strangely like that object: https://github.com/Unicity/PublicModels.json/blob/master/src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json#L270-L302

What is your use case?

2024-09-30 18:16 UTC, daintablian commented on src/classes/Unicity/MappingService/Impl/Hydra/API/Master/Model/Customer.json
> +				"trainerName": {
this is for the vietnam specific fields. you can see the hydra key, unity key, and xdbc key [here](https://github.com/Unicity/Octopus/blob/release/components/services/hydra-app/src/classes/v5/Helper/VNGovernmentInfoHelper.php#L58) , if that gives any context.